### ISSUE TITLE
Slightly more fair scoring system?

### ISSUE THREAD

**Issue by fepettersen** [Andrioden/siage#29]
The way the scoring system works now you can win one match, stop playing entirely and still be somewhere around the middle of the ranking. This is because it is in essence a zero flux system; New points only enter the rating system with a new player. 

I suggest that the number of matches you play have an influence on the score, meaning that e.g. the losing team does not lose points, but the winning team earns twice the points they do today..

**Comment by Andrioden** [comment]
The problem is that the rating will basically be a "who won the most games rating". I dont like this. While you are pointing at a flaw, I dont think your propsal is the solution. The problem you solve (avoid people staying high with few matches) is less of a problem than the one you create (one can farm points by just playing a lot).

**Comment by bjorntore** [comment]
I have to agree with André. We could consider having a decaying rating. For instance, if you don't play for 3 months, you lose 20 rating or something.  

I honestly don't think something like this is necessary though, as most of the guys involved are going to be playing as often as they can. :)
